language: node_js
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: s3
  region: $AWS_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  acl: public_read
  skip_cleanup: true
  local_dir: public
  on:
    branch: master
