language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_e7dc4fe72f7d_key -iv $encrypted_e7dc4fe72f7d_iv -in fonts/fonts.tar.enc -out fonts/fonts.tar -d
  - tar xvf fonts/fonts.tar --directory fonts
script:
  - yarn build
deploy:
  provider: s3
  region: $AWS_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  acl: public_read
  skip_cleanup: true
  local_dir: public
  on:
    branch: master
