os: linux
dist: xenial
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_e7dc4fe72f7d_key -iv $encrypted_e7dc4fe72f7d_iv -in fonts/fonts.tar.enc -out fonts/fonts.tar -d
  - tar xvf fonts/fonts.tar --directory fonts
script:
  - yarn build
after_deploy:
  - ./after-deploy.sh
deploy:
  # Production s3 deployment. This is parallel with master branch.
  - provider: s3
    region: $AWS_REGION
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET_PRODUCTION
    acl: public_read
    local_dir: public
    on:
      branch: master
  # Feature s3 deployment. This is parallel with * branch except master.
  - provider: s3
    region: $AWS_REGION
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET_PREVIEW
    acl: public_read
    local_dir: public
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master