FROM node:13

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN yarn install --freeze && yarn cache clean

COPY .env.example .env.development

# Also exposing VSCode debug ports
EXPOSE 8000

CMD ["yarn", "start", "-H", "0.0.0.0" ]